
services:
  # PHP-FPM (Symfony)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
      - mailer

  # MariaDB
  database:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: escalada_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - database_data:/var/lib/mysql

  # Mailpit (dev mail)
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  # Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - web

  # Adminer (DB UI)
  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      - database

volumes:
  database_data:
