services:
  web:
    image: enlike20/climbup:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - mailer
      - database

  database:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: VivaElBetis
      MYSQL_DATABASE: escalada_db
      MYSQL_USER: climbup_app
      MYSQL_PASSWORD: 5b10a326b930be38a19c8702ea0b7932
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - web

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: climbup-db

volumes:
  database_data: